# .github/workflows/sonarcloud.yml
name: SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET                 #.net will setup2
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          dotnet sonarscanner begin \
            /k:"Radhika-TestEngineer_Dotnet-Sonarcloud" \
            /o:"radhika-testengineer" \
            /d:sonar.host.url="${SONAR_HOST_URL}" \
            /d:sonar.scanner.sonarcloudUrl="${SONAR_HOST_URL}" \
            /d:sonar.login="${SONAR_TOKEN}"

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test with Coverage
        run: |
          dotnet test --no-build -c Release \
            --collect:"XPlat Code Coverage" \
            --results-directory ./coverage

      - name: End SonarCloud
        if: always()
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner end /d:sonar.login="${SONAR_TOKEN}"

     - name: SonarCloud Quality Gate
       if: success()
       uses: sonarsource/sonarqube-quality-gate-action@master
       with:
         scanMetadataReportFile: .scannerwork/report-task.txt
       env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
